# Generated by Django 3.2.12 on 2022-02-22 18:48

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(error_messages={'unique': 'Такое имя пользователя уже занято.'}, help_text='Обязательное. 150 символов или меньше. Только: буквы, числа и @/./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Логин')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(error_messages={'unique': 'Данная почта привязана к другому аккаунту.'}, max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, error_messages={'unique': 'Данный номер привязан к другому аккаунту.'}, max_length=16, unique=True, verbose_name='Телефон')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('is_admin', models.BooleanField(default=False, help_text='Установите в True, если хотите сделать пользователя админом', verbose_name='Админ')),
                ('birthday', models.DateField(blank=True, help_text='Указывайте в формате дд.мм.гггг', null=True, verbose_name='Дата рождения')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('other_name', models.CharField(blank=True, help_text='Не обязательное поле. Максимальная длина - 150 символов', max_length=150, verbose_name='Отчество')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_info.citymodel')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
