# Generated by Django 3.2.12 on 2022-02-23 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_info', '0002_auto_20220222_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_info.citymodel'),
        ),
    ]
