# Generated by Django 4.2.6 on 2023-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_info', '0003_alter_usermodel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=16, verbose_name='Телефон'),
        ),
    ]
